### ISSUE TITLE
Support PyArrow >=0.14

### ISSUE THREAD

**Issue by icexelloss** [omnisci/pymapd#292] opened 2020-02-12 12:51 UTC
Hello,

This is a dev from https://github.com/ibis-project/ibis, we are facing an issue that we are enable to upgrade pyarrow dependency >=0.14 because of pymapd. I wonder if pymapd can support PyArrow >= 0.14? Ideally the newest PyArrow version.

**Comment by randyzwitch** [comment] 2020-02-20 15:02
Duplicate of #245 

It is our goal to move to Arrow 0.15 by the end of this month, and we'll update pymapd at that time as well.

**Closed by randyzwitch** 2020-02-20 15:02 UTC
