### ISSUE TITLE
Upgrade pymapd 0.40 to pymapd 0.60 fails

### ISSUE THREAD

**Issue by kchu-mapd** [omnisci/pymapd#137] opened 2018-12-11 21:33 UTC
I have a QA test laptop that has a successful installation of Pymapd 0.40, and when I try to upgrade it to Pymapd 0.60, it fails with the following error:

The Linux machine is mapd@10.1.1.221 (passwd: mapd1234), running Ubuntu 16.04.

mapd@lidia-Precision-M6800:~/render_test$ sudo python3.6 -m pip install --upgrade pymapd
Collecting pymapd
  Downloading https://files.pythonhosted.org/packages/54/8d/6fe82234aa7873df8c79ef9ee84c44a08bac7c2de84665153939243de1ff/pymapd-0.6.0.tar.gz (93kB)
    100% |████████████████████████████████| 102kB 4.4MB/s 
Collecting six (from pymapd)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Requirement already up-to-date: thrift==0.11.0 in /usr/local/lib/python3.6/dist-packages (from pymapd)
Collecting sqlalchemy (from pymapd)
  Downloading https://files.pythonhosted.org/packages/e2/0a/05b7d13618ad41c108a6c2b886af83bf9bb7e35f8951227abb18b1330745/SQLAlchemy-1.2.14.tar.gz (5.7MB)
    100% |████████████████████████████████| 5.7MB 347kB/s 
Collecting numpy (from pymapd)
  Downloading https://files.pythonhosted.org/packages/ff/7f/9d804d2348471c67a7d8b5f84f9bc59fd1cefa148986f2b74552f8573555/numpy-1.15.4-cp36-cp36m-manylinux1_x86_64.whl (13.9MB)
    100% |████████████████████████████████| 13.9MB 142kB/s 
Collecting pandas (from pymapd)
  Downloading https://files.pythonhosted.org/packages/e1/d8/feeb346d41f181e83fba45224ab14a8d8af019b48af742e047f3845d8cff/pandas-0.23.4-cp36-cp36m-manylinux1_x86_64.whl (8.9MB)
    100% |████████████████████████████████| 8.9MB 224kB/s 
Collecting pyarrow==0.10.0 (from pymapd)
  Downloading https://files.pythonhosted.org/packages/c9/b8/076ebd968f3c6d4e9b6e5de696f0b19964a3d4b7dc020fd32db4e868ad74/pyarrow-0.10.0-cp36-cp36m-manylinux1_x86_64.whl (11.6MB)
    100% |████████████████████████████████| 11.6MB 169kB/s 
Collecting pytz>=2011k (from pandas->pymapd)
  Downloading https://files.pythonhosted.org/packages/f8/0e/2365ddc010afb3d79147f1dd544e5ee24bf4ece58ab99b16fbb465ce6dc0/pytz-2018.7-py2.py3-none-any.whl (506kB)
    100% |████████████████████████████████| 512kB 4.1MB/s 
Collecting python-dateutil>=2.5.0 (from pandas->pymapd)
  Downloading https://files.pythonhosted.org/packages/74/68/d87d9b36af36f44254a8d512cbfc48369103a3b9e474be9bdfe536abfc45/python_dateutil-2.7.5-py2.py3-none-any.whl (225kB)
    100% |████████████████████████████████| 235kB 7.7MB/s 
Building wheels for collected packages: pymapd, sqlalchemy
  Running setup.py bdist_wheel for pymapd ... error
  Complete output from command /usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-kgh4b6ew/pymapd/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpvajh2fijpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/pymapd
  copying pymapd/__init__.py -> build/lib.linux-x86_64-3.6/pymapd
  copying pymapd/connection.py -> build/lib.linux-x86_64-3.6/pymapd
  copying pymapd/_parsers.py -> build/lib.linux-x86_64-3.6/pymapd
  copying pymapd/_pandas_loaders.py -> build/lib.linux-x86_64-3.6/pymapd
  copying pymapd/exceptions.py -> build/lib.linux-x86_64-3.6/pymapd
  copying pymapd/_mutators.py -> build/lib.linux-x86_64-3.6/pymapd
  copying pymapd/_utils.py -> build/lib.linux-x86_64-3.6/pymapd
  copying pymapd/_loaders.py -> build/lib.linux-x86_64-3.6/pymapd
  copying pymapd/dtypes.py -> build/lib.linux-x86_64-3.6/pymapd
  copying pymapd/cursor.py -> build/lib.linux-x86_64-3.6/pymapd
  copying pymapd/compat.py -> build/lib.linux-x86_64-3.6/pymapd
  creating build/lib.linux-x86_64-3.6/mapd
  copying mapd/__init__.py -> build/lib.linux-x86_64-3.6/mapd
  copying mapd/MapD.py -> build/lib.linux-x86_64-3.6/mapd
  copying mapd/ttypes.py -> build/lib.linux-x86_64-3.6/mapd
  copying mapd/constants.py -> build/lib.linux-x86_64-3.6/mapd
  running build_ext
  building 'pymapd.shm' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/pymapd
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -I/usr/local/lib/python3.6/dist-packages/pyarrow/include -I/usr/include/python3.6m -c pymapd/shm.cpp -o build/temp.linux-x86_64-3.6/pymapd/shm.o -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/pymapd/shm.o -larrow -larrow_python -o build/lib.linux-x86_64-3.6/pymapd/shm.cpython-36m-x86_64-linux-gnu.so -std=c++11
  /usr/bin/ld: cannot find -larrow
  /usr/bin/ld: cannot find -larrow_python
  collect2: error: ld returned 1 exit status
  error: command 'x86_64-linux-gnu-g++' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pymapd
  Running setup.py clean for pymapd
  Running setup.py bdist_wheel for sqlalchemy ... done
  Stored in directory: /home/mapd/.cache/pip/wheels/86/c8/99/8d6049a373070743a79ada4cf9798f8130cc8e2dfcd66e0e9d
Successfully built sqlalchemy
Failed to build pymapd
Installing collected packages: six, sqlalchemy, numpy, pytz, python-dateutil, pandas, pyarrow, pymapd
  Found existing installation: six 1.11.0
    Uninstalling six-1.11.0:
      Successfully uninstalled six-1.11.0
  Found existing installation: SQLAlchemy 1.2.9
    Uninstalling SQLAlchemy-1.2.9:
      Successfully uninstalled SQLAlchemy-1.2.9
  Found existing installation: numpy 1.14.5
    Uninstalling numpy-1.14.5:
      Successfully uninstalled numpy-1.14.5
  Found existing installation: pytz 2018.5
    Uninstalling pytz-2018.5:
      Successfully uninstalled pytz-2018.5
  Found existing installation: python-dateutil 2.7.3
    Uninstalling python-dateutil-2.7.3:
      Successfully uninstalled python-dateutil-2.7.3
  Found existing installation: pandas 0.23.3
    Uninstalling pandas-0.23.3:
      Successfully uninstalled pandas-0.23.3
  Found existing installation: pyarrow 0.7.1
    Uninstalling pyarrow-0.7.1:
      Successfully uninstalled pyarrow-0.7.1
  Found existing installation: pymapd 0.4.0
    Uninstalling pymapd-0.4.0:
      Successfully uninstalled pymapd-0.4.0
  Running setup.py install for pymapd ... error
    Complete output from command /usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-kgh4b6ew/pymapd/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-49kv2lt9-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/pymapd
    copying pymapd/__init__.py -> build/lib.linux-x86_64-3.6/pymapd
    copying pymapd/connection.py -> build/lib.linux-x86_64-3.6/pymapd
    copying pymapd/_parsers.py -> build/lib.linux-x86_64-3.6/pymapd
    copying pymapd/_pandas_loaders.py -> build/lib.linux-x86_64-3.6/pymapd
    copying pymapd/exceptions.py -> build/lib.linux-x86_64-3.6/pymapd
    copying pymapd/_mutators.py -> build/lib.linux-x86_64-3.6/pymapd
    copying pymapd/_utils.py -> build/lib.linux-x86_64-3.6/pymapd
    copying pymapd/_loaders.py -> build/lib.linux-x86_64-3.6/pymapd
    copying pymapd/dtypes.py -> build/lib.linux-x86_64-3.6/pymapd
    copying pymapd/cursor.py -> build/lib.linux-x86_64-3.6/pymapd
    copying pymapd/compat.py -> build/lib.linux-x86_64-3.6/pymapd
    creating build/lib.linux-x86_64-3.6/mapd
    copying mapd/__init__.py -> build/lib.linux-x86_64-3.6/mapd
    copying mapd/MapD.py -> build/lib.linux-x86_64-3.6/mapd
    copying mapd/ttypes.py -> build/lib.linux-x86_64-3.6/mapd
    copying mapd/constants.py -> build/lib.linux-x86_64-3.6/mapd
    running build_ext
    building 'pymapd.shm' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/pymapd
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -I/usr/local/lib/python3.6/dist-packages/pyarrow/include -I/usr/include/python3.6m -c pymapd/shm.cpp -o build/temp.linux-x86_64-3.6/pymapd/shm.o -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/pymapd/shm.o -larrow -larrow_python -o build/lib.linux-x86_64-3.6/pymapd/shm.cpython-36m-x86_64-linux-gnu.so -std=c++11
    /usr/bin/ld: cannot find -larrow
    /usr/bin/ld: cannot find -larrow_python
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-g++' failed with exit status 1

**Comment by randyzwitch** [comment] 2019-01-02 19:47
@kchu-mapd Is this still an issue or can I close this?

**Comment by randyzwitch** [comment] 2019-01-05 03:32
If this is still an issue, let me know. But I think the issue is using `sudo pip install`, which messes with the overall global environment. Better to use a conda environment to install pymapd, so that the system libraries don't affect specific installs

**Closed by randyzwitch** 2019-01-05 03:32 UTC
