### ISSUE TITLE
conda recipes omnisci vs conda-forge

### ISSUE THREAD

**Issue by xmnlab** [omnisci/pymapd#143] opened 2019-01-03 16:40 UTC
hey everyone! what is the difference between conda recipes from omnisci and conda-forge?

it seems that on omnisci org it was been used in the past to upload to pymapd channel (https://github.com/omnisci/pymapd/blob/master/ci/upload-anaconda.sh#L25)

**Comment by randyzwitch** [comment] 2019-01-03 16:42
cc: @TomAugspurger 

I wonder if this might be the cause of this issue, as our tests pass before merging a PR to master, but master claims to be broken https://github.com/omnisci/pymapd/issues/113

**Comment by TomAugspurger** [comment] 2019-01-03 16:48
I'm not sure that this is related to #113. That comes from https://travis-ci.org/omnisci/pymapd, which does seem to be failing as of an hour ago.

---

regarding the conda packages, I don't recall why the https://anaconda.org/pymapd/pymapd channel was created. Perhaps as a way to distribute the conda packages before the library was ready for conda-forge. It doesn't seem to be regularly updated. But I would recommend using conda-forge.

**Comment by randyzwitch** [comment] 2019-01-03 16:50
Yes, pymapd is currently failing due to #141, but it's been failing for some time not related to an OmniSci issue.

**Comment by randyzwitch** [comment] 2019-01-03 19:08
Removing all of the conda build/upload references in #144 seems to work fine, and as a side-benefit, speeds up CI considerably. Feels like we can remove that code for both clarity (conda build checking will only happen at pymapd-feedstock) and increased development speed.

**Comment by randyzwitch** [comment] 2019-01-05 03:15
Closed by #144. Removed the conda build steps and now master is passing again. Hopefully this won't affect anything down the line

**Closed by randyzwitch** 2019-01-05 03:15 UTC

**Comment by xmnlab** [comment] 2019-01-07 02:39
thanks @randyzwitch !
