### ISSUE TITLE
execute sometimes returns results from previous call

### ISSUE THREAD

**Issue by mikehinchey** [omnisci/pymapd#82] opened 2018-07-13 17:20 UTC
I'm using pymapd 0.4.0 in jupyter with mapd 4.0.2.  I've seen this happen a few times, and it happened in 0.3.x also.  I just restart the connection or the notebook to work around.

![image](https://user-images.githubusercontent.com/22701/42704708-c416f2be-8685-11e8-8f54-463cebcd3c2d.png)

I don't know how to reproduce. One guess would be when a call to `execute` is killed.

**Comment by randyzwitch** [comment] 2018-09-14 14:28
I just saw this too, but then couldn't reproduce. It's definitely around errors or interrupting the kernel.

**Comment by randyzwitch** [comment] 2018-09-19 13:13
@mikehinchey I wonder if this is the explanation for this behavior

http://blog.steveniemitz.com/introducing-scales-rpc-python/

**Comment by TomAugspurger** [comment] 2018-09-19 13:36
FWIW, `con.execute` does keep state on Cursor under the `_result` attribute: https://github.com/mapd/pymapd/blob/4665ea704eb7ffabf72048f1cb3519b4497b8830/pymapd/cursor.py#L132

I'm not sure how one would go about debugging this.

**Comment by randyzwitch** [comment] 2018-09-19 13:51
Thanks @TomAugspurger. I've been having a lot of issues with pymapd lately, and almost all of them start with "Not sure how to debug this" :(

**Comment by TomAugspurger** [comment] 2018-09-19 14:35
Could maybe add an `except KeyboardInterrupt` https://github.com/mapd/pymapd/blob/master/pymapd/cursor.py#L123. Does the mapd API have a way to cancel a running query? May want to do the same in the `Cursor.__del__` method, but doing that properly may be tricky.

**Comment by randyzwitch** [comment] 2018-09-19 18:36
There is an `interrupt` thrift method defined, I believe to interrupt a query.

**Comment by randyzwitch** [comment] 2020-03-19 18:27
Closing this, since OmniSciDB and pymapd have gone pretty far in 18 months. If this is still an issue, we can re-open this.

**Closed by randyzwitch** 2020-03-19 18:27 UTC
Labels: bug, question
