### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by mlazatinph** [omnisci/pymapd#275] opened 2019-10-17 04:13 UTC
I just installed pymapd via conda install -c conda-forge pymapd.
When I try to import pymapd, I'm getting a segmentation fault.

```
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymadp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pymadp'
>>> import pymapd
/home/bcauser/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/bcauser/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/bcauser/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/bcauser/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/bcauser/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/bcauser/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Segmentation fault (core dumped)
```
This is on Ubuntu 16.04
nvidia-cuda 10.1 is installed

**Comment by randyzwitch** [comment] 2019-10-17 13:39
If I'm not mistaken, this is actually a problem with Tensorflow and Arrow, which happens to arise because we use pyarrow:

https://discuss.python.org/t/crashes-combining-tensorflow-with-other-packages-who-can-reproduce/2029

For now, I'll leave this open to see if there's anything we can do about it.

**Comment by randyzwitch** [comment] 2019-11-12 18:15
Unfortunately, I can't replicate the segfault in a clean conda environment:

```python
Python 3.7.5 (default, Oct 25 2019, 15:51:11) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymapd
>>> import tensorflow
>>> import tensorboard
>>> exit()
(pymapd275) rzwitch@randyzwitch-workstation:~/Desktop$ conda list
# packages in environment at /home/rzwitch/miniconda3/envs/pymapd275:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_tflow_select             2.1.0                       gpu    anaconda
absl-py                   0.8.1                    py37_0  
arrow-cpp                 0.13.0           py37h620436b_3    conda-forge
astor                     0.8.0                    py37_0    anaconda
blas                      1.0                         mkl  
boost-cpp                 1.68.0            h11c811c_1000    conda-forge
brotli                    1.0.7             he1b5a44_1000    conda-forge
bzip2                     1.0.8                h516909a_1    conda-forge
c-ares                    1.15.0            h7b6447c_1001  
ca-certificates           2019.10.16                    0    anaconda
certifi                   2019.9.11                py37_0    anaconda
cudatoolkit               10.0.130                      0    anaconda
cudnn                     7.6.4                cuda10.0_0    anaconda
cupti                     10.0.130                      0    anaconda
gast                      0.2.2                    py37_0    anaconda
gflags                    2.2.2             he1b5a44_1002    conda-forge
glog                      0.4.0                he1b5a44_1    conda-forge
google-pasta              0.1.7                      py_0    anaconda
grpcio                    1.16.1           py37hf8bcb03_1  
h5py                      2.9.0            py37h7918eee_0    anaconda
hdf5                      1.10.4               hb1b8bf9_0    anaconda
icu                       58.2              hf484d3e_1000    conda-forge
intel-openmp              2019.4                      243  
keras-applications        1.0.8                      py_0    anaconda
keras-preprocessing       1.1.0                      py_1    anaconda
libedit                   3.1.20181209         hc058e9b_0  
libevent                  2.1.10               h72c5cf5_0    conda-forge
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libprotobuf               3.7.1                h8b12597_0    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
markdown                  3.1.1                    py37_0  
mkl                       2019.4                      243  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.0.15           py37ha843d7b_0  
mkl_random                1.1.0            py37hd6b4f25_0  
ncurses                   6.1                  he6710b0_1  
numpy                     1.17.3           py37hd14ec0e_0  
numpy-base                1.17.3           py37hde5b4d6_0  
openssl                   1.1.1                h7b6447c_0    anaconda
opt_einsum                3.1.0                      py_0    anaconda
packaging                 19.2                       py_0    conda-forge
pandas                    0.25.3           py37hb3f55d8_0    conda-forge
pip                       19.3.1                   py37_0  
protobuf                  3.7.1            py37he1b5a44_0    conda-forge
pyarrow                   0.13.0           py37he6710b0_0  
pymapd                    0.16.0                     py_0    conda-forge
pyparsing                 2.4.5                      py_0    conda-forge
python                    3.7.5                h0371630_0  
python-dateutil           2.8.1                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
re2                       2019.11.01           he1b5a44_0    conda-forge
readline                  7.0                  h7b6447c_5  
scipy                     1.3.1            py37h7c811a0_0    anaconda
setuptools                41.6.0                   py37_0  
six                       1.13.0                   py37_0  
snappy                    1.1.7             he1b5a44_1002    conda-forge
sqlalchemy                1.3.11           py37h516909a_0    conda-forge
sqlite                    3.30.1               h7b6447c_0  
tensorboard               2.0.0              pyhb230dea_0  
tensorflow                2.0.0           gpu_py37h768510d_0    anaconda
tensorflow-base           2.0.0           gpu_py37h0ec5d1f_0    anaconda
tensorflow-estimator      2.0.0              pyh2649769_0    anaconda
tensorflow-gpu            2.0.0                h0d30ee6_0    anaconda
termcolor                 1.1.0                    py37_1    anaconda
thrift                    0.11.0          py37he1b5a44_1001    conda-forge
thrift-cpp                0.12.0            h0a07b25_1002    conda-forge
tk                        8.6.8                hbc83047_0  
webencodings              0.5.1                    py37_1  
werkzeug                  0.16.0                     py_0  
wheel                     0.33.6                   py37_0  
wrapt                     1.11.2           py37h7b6447c_0    anaconda
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.3                         1    conda-forge
```

Like I mentioned in the other comment, if I had to guess, I'd bet that there is some sort of mangling of C++ symbols between tensorflow and Arrow somehow, and pymapd also having an Arrow dependency gets caught up in the middle. Going to close this issue for now, but if this continues to be an issue, please let us know.

**Closed by randyzwitch** 2019-11-12 18:15 UTC
Labels: apache arrow, question
